spring.application.name: bursdag
server:
  port: 8080


spring:
  data:
    mongodb:
      uuid-representation: standard
      authentication-database: admin
      username: partymaker
      password: secret
      database: partymaker
      host: localhost
      port: 27017

bursdag:
  jwt:
    secretKey: VO87WsCvKviIzkIZzqJK+myPdnLn7DXGuyKHSpJeGNI=
logging:
  level:
    org.springframework.security: WARN
