spring.application.name: bursdag
server:
  port: 8080


spring:
  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard
      authentication-database: admin
      username: partymaker
      password: secret
      database: partymaker
      host: localhost
      port: 27017

resilience4j:
  retry:
    instances:
      party-act:
        base-config: optimistic-log
    configs:
      optimistic-log:
        max-attempts: 3
        wait-duration: 100ms
        retry-exceptions:
          - org.springframework.dao.OptimisticLockingFailureException

partymaker:
  jwt:
    secretKey: VO87WsCvKviIzkIZzqJK+myPdnLn7DXGuyKHSpJeGNI=
logging:
  level:
    root: info
